<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<!DOCTYPE stationlist [
<!ELEMENT stationlist (station)+>
<!ATTLIST stationlist created CDATA #REQUIRED>
<!ELEMENT station (comp)+>
<!ATTLIST station code CDATA #REQUIRED>
<!ATTLIST station name CDATA #REQUIRED>
<!ATTLIST station insttype CDATA #REQUIRED>
<!ATTLIST station lat CDATA #REQUIRED>
<!ATTLIST station lon CDATA #REQUIRED>
<!ATTLIST station source (SCSN | CGS | NSMP) "SCSN">
<!ATTLIST station commtype (DIG | ANA) "DIG">
<!ATTLIST station dist CDATA "10.0">
<!ATTLIST station loc CDATA "">
<!ELEMENT comp (acc , vel , psa*)>
<!ATTLIST comp name CDATA #REQUIRED>
<!ATTLIST comp originalname CDATA #IMPLIED>
<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc value CDATA #REQUIRED>
<!ATTLIST acc flag CDATA "">
<!ATTLIST vel value CDATA #REQUIRED>
<!ATTLIST vel flag CDATA "">
<!ATTLIST psa03 value CDATA #REQUIRED>
<!ATTLIST psa03 flag CDATA "">
<!ATTLIST psa10 value CDATA #REQUIRED>
<!ATTLIST psa10 flag CDATA "">
<!ATTLIST psa30 value CDATA #REQUIRED>
<!ATTLIST psa30 flag CDATA "">
]>
<stationlist created="1509634436">
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ01" name="" netid="3A" lat="42.671575" commtype="DIG" lon="13.270813">
    <comp name="HNZ">
      <acc value="152.039428041"/>
      <vel value="65.407259"/>
      <psa03 value="303.089230267"/>
      <psa10 value="25.7672089857"/>
      <psa30 value="9.58241601362"/>
    </comp>
    <comp name="HNE">
      <acc value="88.0960130116"/>
      <vel value="63.135863"/>
      <psa03 value="190.595157368"/>
      <psa10 value="112.3808844"/>
      <psa30 value="11.489856373"/>
    </comp>
    <comp name="HNN">
      <acc value="147.6386863"/>
      <vel value="154.568256"/>
      <psa03 value="401.286881861"/>
      <psa10 value="104.638179195"/>
      <psa30 value="13.3265692158"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ04" name="" netid="3A" lat="42.673895" commtype="DIG" lon="13.29381">
    <comp name="HNZ">
      <acc value="38.8004897697"/>
      <vel value="39.434096"/>
      <psa03 value="156.200129504"/>
      <psa10 value="31.7652817221"/>
      <psa30 value="12.2577026813"/>
    </comp>
    <comp name="HNE">
      <acc value="64.6265987876"/>
      <vel value="50.075964"/>
      <psa03 value="260.403909592"/>
      <psa10 value="41.5395675384"/>
      <psa30 value="6.58658155435"/>
    </comp>
    <comp name="HNN">
      <acc value="80.8925856434"/>
      <vel value="85.392667"/>
      <psa03 value="129.281660914"/>
      <psa10 value="150.183803847"/>
      <psa30 value="15.0523369346"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ08" name="" netid="3A" lat="42.63254" commtype="DIG" lon="13.286562">
    <comp name="HNZ">
      <acc value="32.7723358129"/>
      <vel value="31.930458"/>
      <psa03 value="78.2871826771"/>
      <psa10 value="20.8313746284"/>
      <psa30 value="5.50712016846"/>
    </comp>
    <comp name="HNE">
      <acc value="53.7131632107"/>
      <vel value="36.952267"/>
      <psa03 value="110.732003283"/>
      <psa10 value="16.2786476524"/>
      <psa30 value="5.0008616602"/>
    </comp>
    <comp name="HNN">
      <acc value="43.581803776"/>
      <vel value="39.09925"/>
      <psa03 value="122.687156164"/>
      <psa10 value="23.9162201159"/>
      <psa30 value="3.61013190029"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ10" name="" netid="3A" lat="42.625117" commtype="DIG" lon="13.29985">
    <comp name="HNZ">
      <acc value="22.9503793854"/>
      <vel value="17.160261"/>
      <psa03 value="32.3984235187"/>
      <psa10 value="20.9073434863"/>
      <psa30 value="5.03794873887"/>
    </comp>
    <comp name="HNE">
      <acc value="31.9021062238"/>
      <vel value="26.864381"/>
      <psa03 value="97.1641692117"/>
      <psa10 value="25.0723743582"/>
      <psa30 value="5.08603855547"/>
    </comp>
    <comp name="HNN">
      <acc value="39.7704614726"/>
      <vel value="43.224876"/>
      <psa03 value="137.087588524"/>
      <psa10 value="18.4473800941"/>
      <psa30 value="5.21972335099"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ102" name="" netid="3A" lat="42.70367" commtype="DIG" lon="13.232048">
    <comp name="HNZ">
      <acc value="31.8538963866"/>
      <vel value="34.189537"/>
      <psa03 value="52.3841474918"/>
      <psa10 value="25.0058888611"/>
      <psa30 value="10.9485910071"/>
    </comp>
    <comp name="HNE">
      <acc value="37.2404113535"/>
      <vel value="43.453647"/>
      <psa03 value="129.628364426"/>
      <psa10 value="44.7023193445"/>
      <psa30 value="12.1953980207"/>
    </comp>
    <comp name="HNN">
      <acc value="40.5064459321"/>
      <vel value="48.078419"/>
      <psa03 value="114.598767163"/>
      <psa10 value="34.840337934"/>
      <psa30 value="8.86686075265"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ11" name="" netid="3A" lat="42.66291" commtype="DIG" lon="13.307648">
    <comp name="HNZ">
      <acc value="8.77719414887"/>
      <vel value="14.754428"/>
      <psa03 value="13.4556652884"/>
      <psa10 value="16.4814692071"/>
      <psa30 value="6.78608903142"/>
    </comp>
    <comp name="HNE">
      <acc value="16.9007047259"/>
      <vel value="15.433591"/>
      <psa03 value="39.201358262"/>
      <psa10 value="32.3378523757"/>
      <psa30 value="2.843988518"/>
    </comp>
    <comp name="HNN">
      <acc value="19.8954928543"/>
      <vel value="41.972474"/>
      <psa03 value="30.1497453259"/>
      <psa10 value="60.4439844391"/>
      <psa30 value="9.61504693244"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ14" name="" netid="3A" lat="42.6254" commtype="DIG" lon="13.357295">
    <comp name="HNZ">
      <acc value="10.9309366603"/>
      <vel value="8.096314"/>
      <psa03 value="35.4694008657"/>
      <psa10 value="8.22611187307"/>
      <psa30 value="3.61997216175"/>
    </comp>
    <comp name="HNE">
      <acc value="21.9166781725"/>
      <vel value="6.921848"/>
      <psa03 value="17.1244002794"/>
      <psa10 value="7.89261368561"/>
      <psa30 value="1.28397566957"/>
    </comp>
    <comp name="HNN">
      <acc value="25.759173724"/>
      <vel value="9.406605"/>
      <psa03 value="53.6804107417"/>
      <psa10 value="9.04567818776"/>
      <psa30 value="3.59619237966"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ19" name="" netid="3A" lat="42.64109" commtype="DIG" lon="13.206917">
    <comp name="HNZ">
      <acc value="20.8467295152"/>
      <vel value="20.656134"/>
      <psa03 value="39.649421566"/>
      <psa10 value="16.0197417059"/>
      <psa30 value="5.76266105143"/>
    </comp>
    <comp name="HNE">
      <acc value="36.3105344843"/>
      <vel value="34.599686"/>
      <psa03 value="107.609632239"/>
      <psa10 value="29.923266355"/>
      <psa30 value="5.03099427429"/>
    </comp>
    <comp name="HNN">
      <acc value="40.3361603606"/>
      <vel value="21.571276"/>
      <psa03 value="81.7253598324"/>
      <psa10 value="22.4846405245"/>
      <psa30 value="6.3954969332"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ24" name="" netid="3A" lat="42.655239" commtype="DIG" lon="13.288519">
    <comp name="HNZ">
      <acc value="26.5332200089"/>
      <vel value="31.041522"/>
      <psa03 value="44.1642150989"/>
      <psa10 value="30.7498483172"/>
      <psa30 value="6.2032702299"/>
    </comp>
    <comp name="HNE">
      <acc value="102.140211387"/>
      <vel value="55.040907"/>
      <psa03 value="202.362682465"/>
      <psa10 value="70.5703782637"/>
      <psa30 value="6.34388909566"/>
    </comp>
    <comp name="HNN">
      <acc value="76.2485635768"/>
      <vel value="73.604492"/>
      <psa03 value="157.153564163"/>
      <psa10 value="96.3772542102"/>
      <psa30 value="7.77182830018"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ27" name="" netid="3A" lat="42.612412" commtype="DIG" lon="13.296578">
    <comp name="HNZ">
      <acc value="27.0015623072"/>
      <vel value="26.875356"/>
      <psa03 value="34.5724584848"/>
      <psa10 value="27.9757103598"/>
      <psa30 value="4.13975210699"/>
    </comp>
    <comp name="HNE">
      <acc value="20.33931006"/>
      <vel value="18.878698"/>
      <psa03 value="52.8947193996"/>
      <psa10 value="30.2553879255"/>
      <psa30 value="4.44620742047"/>
    </comp>
    <comp name="HNN">
      <acc value="20.6181680798"/>
      <vel value="26.399357"/>
      <psa03 value="43.2056818587"/>
      <psa10 value="26.9458989563"/>
      <psa30 value="4.43679543983"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ29" name="" netid="3A" lat="42.6304" commtype="DIG" lon="13.2925">
    <comp name="HNZ">
      <acc value="22.2773317086"/>
      <vel value="21.96214"/>
      <psa03 value="32.0987289237"/>
      <psa10 value="18.7420780797"/>
      <psa30 value="5.17955672936"/>
    </comp>
    <comp name="HNE">
      <acc value="68.896697649"/>
      <vel value="33.575561"/>
      <psa03 value="134.603559829"/>
      <psa10 value="19.8010533668"/>
      <psa30 value="4.47186348039"/>
    </comp>
    <comp name="HNN">
      <acc value="41.2750330643"/>
      <vel value="35.917068"/>
      <psa03 value="82.5782504729"/>
      <psa10 value="22.3225056467"/>
      <psa30 value="4.88502189841"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ30" name="" netid="3A" lat="42.626432" commtype="DIG" lon="13.29058">
    <comp name="HNZ">
      <acc value="30.3184002692"/>
      <vel value="35.727686"/>
      <psa03 value="75.0235809374"/>
      <psa10 value="22.4290659909"/>
      <psa30 value="5.44769110756"/>
    </comp>
    <comp name="HNE">
      <acc value="46.2394640372"/>
      <vel value="42.696154"/>
      <psa03 value="146.918672533"/>
      <psa10 value="47.5307062045"/>
      <psa30 value="5.37003971795"/>
    </comp>
    <comp name="HNN">
      <acc value="48.357861859"/>
      <vel value="48.934056"/>
      <psa03 value="142.119888035"/>
      <psa10 value="41.5106075979"/>
      <psa30 value="4.86185394605"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ50" name="" netid="3A" lat="42.598" commtype="DIG" lon="13.218">
    <comp name="HNZ">
      <acc value="13.9922372064"/>
      <vel value="20.699694"/>
      <psa03 value="21.7542178012"/>
      <psa10 value="27.1880815569"/>
      <psa30 value="7.79729061402"/>
    </comp>
    <comp name="HNE">
      <acc value="27.1537481199"/>
      <vel value="44.968146"/>
      <psa03 value="60.6105040967"/>
      <psa10 value="65.123054254"/>
      <psa30 value="9.49822824308"/>
    </comp>
    <comp name="HNN">
      <acc value="20.4071674833"/>
      <vel value="30.569058"/>
      <psa03 value="57.752443495"/>
      <psa10 value="43.4332825175"/>
      <psa30 value="12.469701682"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ51" name="" netid="3A" lat="42.637948" commtype="DIG" lon="13.285578">
    <comp name="HNZ">
      <acc value="30.7570809604"/>
      <vel value="39.87922"/>
      <psa03 value="70.1890044001"/>
      <psa10 value="34.8245323327"/>
      <psa30 value="8.12617968419"/>
    </comp>
    <comp name="HNE">
      <acc value="62.4703552181"/>
      <vel value="40.982217"/>
      <psa03 value="139.413561206"/>
      <psa10 value="29.3186766123"/>
      <psa30 value="7.61857515054"/>
    </comp>
    <comp name="HNN">
      <acc value="96.5927572617"/>
      <vel value="74.983793"/>
      <psa03 value="288.894780583"/>
      <psa10 value="43.543819755"/>
      <psa30 value="5.88703583793"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ61" name="" netid="3A" lat="42.634324" commtype="DIG" lon="13.314377">
    <comp name="HNZ">
      <acc value="27.6284953577"/>
      <vel value="18.060036"/>
      <psa03 value="70.5988283461"/>
      <psa10 value="12.8434276741"/>
      <psa30 value="6.01257310091"/>
    </comp>
    <comp name="HNE">
      <acc value="31.8789916026"/>
      <vel value="20.81266"/>
      <psa03 value="98.2207991516"/>
      <psa10 value="24.6167651543"/>
      <psa30 value="3.41721178996"/>
    </comp>
    <comp name="HNN">
      <acc value="54.476546833"/>
      <vel value="38.094775"/>
      <psa03 value="139.115804072"/>
      <psa10 value="21.1563581855"/>
      <psa30 value="5.72829661505"/>
    </comp>
  </station>
  <station insttype="" source="Centro di microzonazione sismica Network, 2016 Central Italy seismic sequence" code="MZ63" name="" netid="3A" lat="42.629805" commtype="DIG" lon="13.323448">
    <comp name="HNZ">
      <acc value="11.1619161487"/>
      <vel value="12.802183"/>
      <psa03 value="15.2931939041"/>
      <psa10 value="9.63763364656"/>
      <psa30 value="5.64028490871"/>
    </comp>
    <comp name="HNE">
      <acc value="24.4080854318"/>
      <vel value="13.436051"/>
      <psa03 value="80.293780241"/>
      <psa10 value="18.5277337317"/>
      <psa30 value="2.68328124283"/>
    </comp>
    <comp name="HNN">
      <acc value="38.4442490555"/>
      <vel value="31.321865"/>
      <psa03 value="83.1315484901"/>
      <psa10 value="18.9574421439"/>
      <psa30 value="5.68777309275"/>
    </comp>
  </station>
  <station insttype="" source="Albanian Seismic Network" code="DURR" name="" netid="AC" lat="41.3199" commtype="DIG" lon="19.4573">
    <comp name="HNZ">
      <acc value="0.0473872321333"/>
      <vel value="0.290745"/>
      <psa03 value="0.0840610198182"/>
      <psa10 value="0.111671161916"/>
      <psa30 value="0.0895279223792"/>
    </comp>
    <comp name="HNE">
      <acc value="0.104515303391"/>
      <vel value="0.579367"/>
      <psa03 value="0.131718782663"/>
      <psa10 value="0.204816119674"/>
      <psa30 value="0.172293290777"/>
    </comp>
    <comp name="HNN">
      <acc value="0.0942464552115"/>
      <vel value="0.71152"/>
      <psa03 value="0.169269832206"/>
      <psa10 value="0.21780118593"/>
      <psa30 value="0.233754646082"/>
    </comp>
  </station>
  <station insttype="" source="Albanian Seismic Network" code="KBN" name="" netid="AC" lat="40.6232" commtype="DIG" lon="20.7874">
    <comp name="HNZ">
      <acc value="0.011674017121"/>
      <vel value="0.061157"/>
      <psa03 value="0.0161924816324"/>
      <psa10 value="0.0283720740518"/>
      <psa30 value="0.0142898951222"/>
    </comp>
    <comp name="HNE">
      <acc value="0.0128492400565"/>
      <vel value="0.062826"/>
      <psa03 value="0.0289111980136"/>
      <psa10 value="0.0357043434812"/>
      <psa30 value="0.0137476100401"/>
    </comp>
    <comp name="HNN">
      <acc value="0.0232867492977"/>
      <vel value="0.058767"/>
      <psa03 value="0.0415118312574"/>
      <psa10 value="0.0489772756242"/>
      <psa30 value="0.015311548796"/>
    </comp>
  </station>
  <station insttype="" source="Albanian Seismic Network" code="TPE" name="" netid="AC" lat="40.2948" commtype="DIG" lon="20.0155">
    <comp name="HNZ">
      <acc value="0.0162839501767"/>
      <vel value="0.053019"/>
      <psa03 value="0.0315458387931"/>
      <psa10 value="0.036130380915"/>
      <psa30 value="0.0193063890319"/>
    </comp>
    <comp name="HNE">
      <acc value="0.0278138813968"/>
      <vel value="0.110011"/>
      <psa03 value="0.0487337673925"/>
      <psa10 value="0.0561129437677"/>
      <psa30 value="0.0163846981385"/>
    </comp>
    <comp name="HNN">
      <acc value="0.0232875650706"/>
      <vel value="0.070176"/>
      <psa03 value="0.0487868946072"/>
      <psa10 value="0.0567877919575"/>
      <psa30 value="0.0257638439222"/>
    </comp>
  </station>
  <station insttype="" source="Universita della Basilicata Seismic Network" code="PZUN" name="" netid="BA" lat="40.6458" commtype="DIG" lon="15.807">
    <comp name="HNZ">
      <acc value="0.0404100278892"/>
      <vel value="0.320823"/>
      <psa03 value="0.0483948137233"/>
      <psa10 value="0.0929364257927"/>
      <psa30 value="0.0739563459489"/>
    </comp>
    <comp name="HNE">
      <acc value="0.060122773832"/>
      <vel value="0.364846"/>
      <psa03 value="0.0709549132476"/>
      <psa10 value="0.116033507875"/>
      <psa30 value="0.162003334472"/>
    </comp>
    <comp name="HNN">
      <acc value="0.0653386222614"/>
      <vel value="0.422956"/>
      <psa03 value="0.088800150918"/>
      <psa10 value="0.128290496755"/>
      <psa30 value="0.203576144759"/>
    </comp>
  </station>
  <station insttype="" source="Regional Seismic Network of North Western Italy" code="FIVI" name="" netid="GU" lat="44.2393" commtype="DIG" lon="10.1273">
    <comp name="HNZ">
      <acc value="0.0302304048783"/>
      <vel value="0.149723"/>
      <psa03 value="0.0471375036327"/>
      <psa10 value="0.0597731131426"/>
      <psa30 value="0.0463267272718"/>
    </comp>
    <comp name="HNE">
      <acc value="0.0493585475162"/>
      <vel value="0.173346"/>
      <psa03 value="0.116863556872"/>
      <psa10 value="0.118506319691"/>
      <psa30 value="0.0495725859493"/>
    </comp>
    <comp name="HNN">
      <acc value="0.0559942488006"/>
      <vel value="0.158214"/>
      <psa03 value="0.109423707382"/>
      <psa10 value="0.0753805835836"/>
      <psa30 value="0.0356083881856"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="0CAN" name="" netid="IT" lat="43.472301" commtype="DIG" lon="12.6308">
    <comp name="HGN">
      <acc value="1.35771848695"/>
      <vel value="0.92249"/>
      <psa03 value="2.70160554318"/>
      <psa10 value="0.793411613548"/>
      <psa30 value="0.221426277067"/>
    </comp>
    <comp name="HGE">
      <acc value="1.75895377117"/>
      <vel value="0.828576"/>
      <psa03 value="4.63419210434"/>
      <psa10 value="0.698783988416"/>
      <psa30 value="0.212117287759"/>
    </comp>
    <comp name="HGZ">
      <acc value="1.15976719879"/>
      <vel value="0.790867"/>
      <psa03 value="2.88426730841"/>
      <psa10 value="0.812411985744"/>
      <psa30 value="0.256162909862"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="0MBT" name="" netid="IT" lat="43.462101" commtype="DIG" lon="12.2488">
    <comp name="HGN">
      <acc value="2.30367424146"/>
      <vel value="2.753062"/>
      <psa03 value="6.66166325911"/>
      <psa10 value="4.22646877374"/>
      <psa30 value="1.08399912304"/>
    </comp>
    <comp name="HGE">
      <acc value="2.20667995697"/>
      <vel value="2.311232"/>
      <psa03 value="6.29771634554"/>
      <psa10 value="3.48472720042"/>
      <psa30 value="1.31270107529"/>
    </comp>
    <comp name="HGZ">
      <acc value="0.956485955958"/>
      <vel value="1.886015"/>
      <psa03 value="2.26582981956"/>
      <psa10 value="2.05899058292"/>
      <psa30 value="0.652736663387"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="0PIO" name="" netid="IT" lat="43.587299" commtype="DIG" lon="12.5127">
    <comp name="HGN">
      <acc value="0.789672518138"/>
      <vel value="0.353549"/>
      <psa03 value="1.8079874371"/>
      <psa10 value="0.256424976929"/>
      <psa30 value="0.0559609040804"/>
    </comp>
    <comp name="HGE">
      <acc value="0.681104556602"/>
      <vel value="0.406348"/>
      <psa03 value="1.39168829315"/>
      <psa10 value="0.429574829325"/>
      <psa30 value="0.0780841571791"/>
    </comp>
    <comp name="HGZ">
      <acc value="0.499228584685"/>
      <vel value="0.304686"/>
      <psa03 value="1.51658313491"/>
      <psa10 value="0.27020848098"/>
      <psa30 value="0.0993517664034"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="0REN" name="" netid="IT" lat="43.5462" commtype="DIG" lon="12.264">
    <comp name="HGN">
      <acc value="0.328081760846"/>
      <vel value="1.123105"/>
      <psa03 value="0.871401548949"/>
      <psa10 value="0.501270056543"/>
      <psa30 value="0.529351001616"/>
    </comp>
    <comp name="HGE">
      <acc value="0.296764338485"/>
      <vel value="0.908322"/>
      <psa03 value="0.702455986499"/>
      <psa10 value="0.59940754488"/>
      <psa30 value="0.367877919575"/>
    </comp>
    <comp name="HGZ">
      <acc value="0.327194505769"/>
      <vel value="0.915355"/>
      <psa03 value="0.627182575089"/>
      <psa10 value="0.445752627044"/>
      <psa30 value="0.936599144458"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="0UM8" name="" netid="IT" lat="43.3041" commtype="DIG" lon="12.341">
    <comp name="HGN">
      <acc value="3.40947428531"/>
      <vel value="3.063696"/>
      <psa03 value="5.94555735139"/>
      <psa10 value="5.08142943819"/>
      <psa30 value="0.847550386727"/>
    </comp>
    <comp name="HGE">
      <acc value="2.85561052959"/>
      <vel value="2.99552"/>
      <psa03 value="6.17522803404"/>
      <psa10 value="4.59904248648"/>
      <psa30 value="1.70530201445"/>
    </comp>
    <comp name="HGZ">
      <acc value="1.50320955678"/>
      <vel value="1.598412"/>
      <psa03 value="3.11055253323"/>
      <psa10 value="3.84610442914"/>
      <psa30 value="0.566523736444"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="ACC" name="" netid="IT" lat="42.695999" commtype="DIG" lon="13.242">
    <comp name="HGN">
      <acc value="39.2280649355"/>
      <vel value="39.412142"/>
      <psa03 value="115.122901297"/>
      <psa10 value="63.1319563765"/>
      <psa30 value="7.01293510016"/>
    </comp>
    <comp name="HGE">
      <acc value="43.425860411"/>
      <vel value="44.111754"/>
      <psa03 value="138.406081587"/>
      <psa10 value="38.1136269776"/>
      <psa30 value="8.81755747376"/>
    </comp>
    <comp name="HGZ">
      <acc value="55.7679163629"/>
      <vel value="23.906312"/>
      <psa03 value="59.5849755013"/>
      <psa10 value="25.9895071202"/>
      <psa30 value="5.88623026212"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="ACT" name="" netid="IT" lat="42.771301" commtype="DIG" lon="13.4125">
    <comp name="HGN">
      <acc value="40.0394817802"/>
      <vel value="10.036272"/>
      <psa03 value="20.7918096394"/>
      <psa10 value="6.28209429316"/>
      <psa30 value="2.03220263801"/>
    </comp>
    <comp name="HGE">
      <acc value="27.9085417548"/>
      <vel value="5.585785"/>
      <psa03 value="11.0105897529"/>
      <psa10 value="5.22670840705"/>
      <psa30 value="0.750834382791"/>
    </comp>
    <comp name="HGZ">
      <acc value="25.4030965722"/>
      <vel value="6.403698"/>
      <psa03 value="15.9188917724"/>
      <psa10 value="7.86878291771"/>
      <psa30 value="2.4063773052"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="AMT" name="" netid="IT" lat="42.63246" commtype="DIG" lon="13.286176">
    <comp name="HGN">
      <acc value="40.1393191355"/>
      <vel value="33.515009"/>
      <psa03 value="132.801721281"/>
      <psa10 value="23.1423574819"/>
      <psa30 value="2.75869945394"/>
    </comp>
    <comp name="HGE">
      <acc value="53.1901957345"/>
      <vel value="37.914697"/>
      <psa03 value="68.9616739661"/>
      <psa10 value="17.8517638541"/>
      <psa30 value="5.61413938501"/>
    </comp>
    <comp name="HGZ">
      <acc value="32.4083669755"/>
      <vel value="31.39542"/>
      <psa03 value="73.2304099769"/>
      <psa10 value="20.7467381828"/>
      <psa30 value="5.41088954944"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="ANB" name="" netid="IT" lat="43.59229" commtype="DIG" lon="13.507411">
    <comp name="HGN">
      <acc value="5.00206370167"/>
      <vel value="2.692145"/>
      <psa03 value="16.5035970489"/>
      <psa10 value="3.56167498585"/>
      <psa30 value="0.551898966518"/>
    </comp>
    <comp name="HGE">
      <acc value="4.07763211698"/>
      <vel value="3.200475"/>
      <psa03 value="11.464261496"/>
      <psa10 value="3.79103975364"/>
      <psa30 value="0.600734195673"/>
    </comp>
    <comp name="HGZ">
      <acc value="2.21219733548"/>
      <vel value="1.640653"/>
      <psa03 value="7.556086941"/>
      <psa10 value="1.21853028302"/>
      <psa30 value="0.350710997129"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="ANT" name="" netid="IT" lat="42.41811" commtype="DIG" lon="13.078598">
    <comp name="HGN">
      <acc value="5.57227564969"/>
      <vel value="6.842756"/>
      <psa03 value="8.86794165184"/>
      <psa10 value="7.39282017814"/>
      <psa30 value="1.23374444892"/>
    </comp>
    <comp name="HGE">
      <acc value="4.45069498758"/>
      <vel value="5.734942"/>
      <psa03 value="8.98675898497"/>
      <psa10 value="5.13884965814"/>
      <psa30 value="1.10489310825"/>
    </comp>
    <comp name="HGZ">
      <acc value="2.46363681787"/>
      <vel value="3.009771"/>
      <psa03 value="5.09568507084"/>
      <psa10 value="4.06220268899"/>
      <psa30 value="1.21053570791"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="AQA" name="" netid="IT" lat="42.37553" commtype="DIG" lon="13.339298">
    <comp name="HGN">
      <acc value="3.51908041992"/>
      <vel value="4.623932"/>
      <psa03 value="10.1507650421"/>
      <psa10 value="4.82373695401"/>
      <psa30 value="1.69131150801"/>
    </comp>
    <comp name="HGE">
      <acc value="3.618444117"/>
      <vel value="4.599932"/>
      <psa03 value="5.88372176023"/>
      <psa10 value="6.21933076025"/>
      <psa30 value="1.34918652139"/>
    </comp>
    <comp name="HGZ">
      <acc value="2.02859753331"/>
      <vel value="3.720352"/>
      <psa03 value="3.96403460917"/>
      <psa10 value="4.47717620186"/>
      <psa30 value="2.09727072956"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="AQF" name="" netid="IT" lat="42.380539" commtype="DIG" lon="13.35474">
    <comp name="HGN">
      <acc value="5.72404460239"/>
      <vel value="5.397912"/>
      <psa03 value="21.5564948275"/>
      <psa10 value="3.71698796225"/>
      <psa30 value="2.92133399275"/>
    </comp>
    <comp name="HGE">
      <acc value="5.40250034415"/>
      <vel value="3.664595"/>
      <psa03 value="10.8056267941"/>
      <psa10 value="3.32076703054"/>
      <psa30 value="1.0115034186"/>
    </comp>
    <comp name="HGZ">
      <acc value="4.73608051679"/>
      <vel value="3.689274"/>
      <psa03 value="16.6833730173"/>
      <psa10 value="3.36203494567"/>
      <psa30 value="2.52394038739"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="AQG" name="" netid="IT" lat="42.373474" commtype="DIG" lon="13.337026">
    <comp name="HGN">
      <acc value="7.70194796388"/>
      <vel value="5.50464"/>
      <psa03 value="15.4363620604"/>
      <psa10 value="9.14353015556"/>
      <psa30 value="1.78001662137"/>
    </comp>
    <comp name="HGE">
      <acc value="5.39038795103"/>
      <vel value="5.543463"/>
      <psa03 value="8.66471221059"/>
      <psa10 value="4.8925372069"/>
      <psa30 value="1.50324524685"/>
    </comp>
    <comp name="HGZ">
      <acc value="3.20064578628"/>
      <vel value="3.637784"/>
      <psa03 value="4.10132920008"/>
      <psa10 value="4.05914354035"/>
      <psa30 value="2.17139390108"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="AQK" name="" netid="IT" lat="42.344967" commtype="DIG" lon="13.400949">
    <comp name="HGN">
      <acc value="6.84171567253"/>
      <vel value="14.74944"/>
      <psa03 value="14.499446804"/>
      <psa10 value="18.0864005547"/>
      <psa30 value="3.60346295626"/>
    </comp>
    <comp name="HGE">
      <acc value="6.26560864311"/>
      <vel value="13.534635"/>
      <psa03 value="9.58822839604"/>
      <psa10 value="11.1214329052"/>
      <psa30 value="3.08390734858"/>
    </comp>
    <comp name="HGZ">
      <acc value="4.2417308663"/>
      <vel value="4.790536"/>
      <psa03 value="7.98723315301"/>
      <psa10 value="6.47583017646"/>
      <psa30 value="1.23792528539"/>
    </comp>
  </station>
  <station insttype="" source="DPC, Dipartimento Protezione Civile" code="AQV" name="" netid="IT" lat="42.377222" commtype="DIG" lon="13.343888">
    <comp name="HGN">
      <acc value="7.30123742562"/>
      <vel value="4.867636"/>
      <psa03 value="16.2806870848"/>
      <psa10 value="4.97645985122"/>
      <psa30 value="2.07446987503"/>
    </comp>
    <comp name="HGE">
      <acc value="6.43805672681"/>
      <vel value="4.995245"/>